<?php include 'header.phtml' ?>

    <div class="container-fluid">
        <div class="row">
            <?php include 'sidebar.phtml' ?>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
       align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Add Product</h1>
                    <?php echo isset($data['msg'])?$data['msg']:''; ?>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week   
                        </button>
                    </div>
                </div>

                <form action="/panel/addProduct" method="POST" enctype="multipart/form-data" class="row g-3">
                    <div class="col-md-6">
                        <label for="name" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="col-md-6">
                        <label for="category" class="form-label">Category</label>
                        <select name="category" id="category">\
                            <option value = "none1">None</option>
                            <option value = "science">Science</option>
                            <option value = "fashion">Fashion</option>
                            <option value = "educational">Educational</option>
                            <option value = "sports">Sports</option>
                            <option value = "other">Other</option>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="description" class="form-label">Description</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="col-md-6">
                        <label for="price" class="form-label">Product Price</label>
                        <input type="number" class="form-control" id="price" name="price">
                    </div>                 
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary" name="publish">Publish</button>
                    </div>

                </form>
            </main>
        </div>
    </div>