<?php
// echo "<pre>";
// print_r($page->getItems());
// echo "</pre>";

// die();
?>
<?php include 'header.phtml'; ?>

  <div class="container-fluid">
    <div class="row">
    <?php include 'sidebar.phtml'; ?>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <?php
        if ($this->session->loginUser->role == 'admin') {
        ?>
          <div class="d-flex justify-content-between flex-wrap 
          flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

          <h2>Users</h2>
          <form action="/panel/allUsers" method="POST" class="row row-cols-lg-auto g-3 align-items-center">
            <div class="col-12">
                <label class="visually-hidden" for="inlineFormInputGroupUsername">Search</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="inlineFormInputGroupUsername" 
                    name="searchField" placeholder="Enter id,name...">
                </div>
            </div>

            <div class="col-12">
                <button type="submit" name="searchUser" class="btn btn-primary">Search</button>
            </div>
        </form>

            <div class="col-12">
              <a class="btn btn-success" href="/signup">Add User</a>
            </div>
          <div class="table-responsive">
            <form action="alterUser" method="POST">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">Full Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Role</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
                  
                </tr>
              </thead>
              <tbody>
                <?php
                foreach ($page->getItems() as $value) {
                    echo "<tr>
                  <td>" . $value['id'] . "</td>
                  <td>" . $value['name'] . "</td>
                  <td>" . $value['email'] . "</td>
                  <td>" . $value['role'] . "</td>
                  <td>" . $value['status'] . "</td>";

                  if ($value['status'] == "Not Approved") {
                        echo "<td><button class='btn btn-success' 
                      type='submit' name = 'approve' value = " . $value['id']. ">
                      Approve</button>

  ";
                    } elseif ($value['role'] !='admin') {
                      echo "<td><button class='btn btn-danger' 
                      type='submit' name = 'restrict' value = " . $value['id'] . ">
                      Restrict</button>
  ";
                    }
                    if ($value['role'] !='admin') {
                    echo "<button class='btn btn-danger' type='submit' 
                  name = 'deleteUser' value = " . $value['id'] . ">Delete</button></td>
  </td></tr> ";}
                  }
                
                ?>
              </tbody>
            </table>
            
            <a href="/panel/allUsers">First</a>
            <a href="/panel/allUsers?page=<?= $page->getPrevious(); ?>">Previous</a>
            <a href="/panel/allUsers?page=<?= $page->getNext(); ?>">Next</a>
            <a href="/panel/allUsers?page=<?= $page->getLast(); ?>">Last</a>

            <?php echo "Page {$page->getCurrent()}  of {$page->getLast()}"; ?>
            </form>
          </div>
          
        <?php } elseif ($this->session->loginUser->role == 'User') {
        ?>

          <h1 class="h3 mb-3 fw-normal">Hello&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->session->loginUser->name; ?></h1>
          <hr>
          <form action="" method="post">
            <h1 class="h3 mb-3 fw-normal">My Profile</h1>

            <div class="form-floating">
              <input type="text" class="form-control" id="floatingInput" name="full_name" placeholder="Full Name" value="<?php echo $this->session->loginUser->name; ?>" disabled>
              <label for="floatingInput">Full Name</label>
            </div>

            <div class="form-floating">
              <input type="text" class="form-control" id="floatingInput" name="email" placeholder="Full Name" value="<?php echo $this->session->loginUser->email; ?>" disabled>
              <label for="floatingInput">Email</label>
            </div>

            <div class="form-floating">
              <input type="text" class="form-control" id="floatingInput" name="role" placeholder="Role" value="<?php echo $this->session->loginUser->role; ?>" disabled>
              <label for="floatingInput">Role</label>
            </div>


            <!-- <button class="w-100 btn btn-lg btn-primary" type="submit" name="submit" value="update">Update</button> -->
            <p class="mt-5 mb-3 text-muted">&copy; CEDCOSS Technologies</p>
          </form>

        <?php } ?>
      </main>
    </div>