<?php include 'header.phtml'; ?>
    <div class="row">
    <?php include 'sidebar.phtml'; ?>
     <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
         <?php
            if ($this->session->loginUser->role == 'admin') {
            ?>
             <div class="d-flex justify-content-between flex-wrap 
          flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                 <div class="btn-toolbar mb-2 mb-md-0">
                     <div class="btn-group me-2">
                         <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                         <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                     </div>
                     <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                         <span data-feather="calendar"></span>
                         This week
                     </button>
                 </div>
             </div>

             <h2>Users</h2>

             <div class="table-responsive">
                 <form action="userAction" method="POST">
                     <table class="table table-striped table-sm">
                         <thead>
                             <tr>
                                 <th scope="col">ID</th>
                                 <th scope="col">Full Name</th>
                                 <th scope="col">Email</th>
                                 <th scope="col">Role</th>
                                 <th scope="col">Status</th>

                             </tr>
                         </thead>
                         <tbody>
                             <?php
                                foreach ($userData as $value) {
                                    echo "<tr>
                  <td>" . $value->id . "</td>
                  <td>" . $value->name . "</td>
                  <td>" . $value->email . "</td>
                  <td>" . $value->role . "</td>
                  <td>" . $value->status . "</td>";
                                }

                                ?>
                         </tbody>
                     </table>

                     <h2>Products</h2>

                     <table class="table table-striped table-sm">
                         <thead>
                             <tr>
                                 <th scope="col">ID</th>
                                 <th scope="col">Name</th>
                                 <th scope="col">Category</th>
                                 <th scope="col">Description</th>
                                 <th scope="col">Price</th>
                             </tr>
                         </thead>
                         <tbody>
                             <?php
                                foreach ($productData as $value) {
                                    echo "<tr>
                                        <td>" . $value->id . "</td>
                                        <td>" . $value->name . "</td>
                                        <td>" . $value->category . "</td>
                                        <td>" . $value->description . "</td>
                                        <td>" . $value->price . "</td>";
                                                        }
                                ?>
                         </tbody>
                     </table>
                 </form>
             </div>

         <?php } elseif ($this->session->loginUser->role == 'User') {
            ?>

             <h1 class="h3 mb-3 fw-normal">Hello&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->session->loginUser->name; ?></h1>
             <hr>
             <form action="" method="post">
                 <h1 class="h3 mb-3 fw-normal">My Profile</h1>

                 <div class="form-floating">
                     <input type="text" class="form-control" id="floatingInput" name="full_name" placeholder="Full Name" value="<?php echo $this->session->loginUser->name; ?>" disabled>
                     <label for="floatingInput">Full Name</label>
                 </div>

                 <div class="form-floating">
                     <input type="text" class="form-control" id="floatingInput" name="email" placeholder="Full Name" value="<?php echo $this->session->loginUser->email; ?>" disabled>
                     <label for="floatingInput">Email</label>
                 </div>

                 <div class="form-floating">
                     <input type="text" class="form-control" id="floatingInput" name="role" placeholder="Role" value="<?php echo $this->session->loginUser->role; ?>" disabled>
                     <label for="floatingInput">Role</label>
                 </div>


                 <!-- <button class="w-100 btn btn-lg btn-primary" type="submit" name="submit" value="update">Update</button> -->
                 <p class="mt-5 mb-3 text-muted">&copy; CEDCOSS Technologies</p>
             </form>

         <?php } ?>
     </main>
     </div>