<?php include 'header.phtml' ?>

<div class="container-fluid">
  <div class="row">
  <?php include 'sidebar.phtml' ?>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap 
      flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Product</h1>


        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <form action="alterProduct" method="POST" class="row g-3">
        <div class="col-md-6">
          <label for="id" class="form-label">Product ID</label>
          <input type="text" class="form-control" id="id" name="post_id" 
          value="<?php echo $data->id; ?>" disabled>
        </div>
        <div class="col-md-6">
          <label for="title" class="form-label">Product Name</label>
          <input type="text" class="form-control" id="name" name="name" value="<?php echo $data->name; ?>">
        </div>
        <div class="col-md-6">
        <label for="category" class="form-label">Category</label>
                      <select name="category" id="category">\
                          <option value = "none1">None</option>
                          <option value = "science">Science</option>
                          <option value = "fashion">Fashion</option>
                          <option value = "educational">Educational</option>
                          <option value = "sports">Sports</option>
                          <option value = "other">Other</option>
        </select>
        </div>
        <div class="col-md-6">
          <label for="title" class="form-label">Product Price</label>
          <input type="text" class="form-control" id="price" name="price" value="<?php echo $data->price; ?>">
        </div>
        <div class="col-md-6">
          <label for="description" class="form-label">Description</label>
          <textarea class="form-control" id="description" name="description" value="<?php echo $data->description; ?>">
            <?php echo $data->description; ?>
          </textarea>
        </div>
        
        <div class="col-12">
          <button type="submit" class="btn btn-primary" name="updateProduct" 
          value="<?php echo $data->id; ?>">Update Product</button>
        </div>

      </form>
    </main>
  </div>
</div>