<?php include 'header.phtml' ?>
    <div class="row">
    <?php include 'sidebar.phtml' ?>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap
         flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Orders</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                    <span data-feather="calendar"></span>
                    This week
                </button>
            </div>
        </div>

        <div class="table-responsive">
        <form action="alterProduct" method="POST">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Order ID</th>
                            <th scope="col">Email</th>
                            <th scope="col">Product Name</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                           
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach ($data as $key => $value) {
                                echo "<tr>
                  <td>" . $value->id . "</td>
                  <td>" . $value->email . "</td>
                  <td>" . $value->product_name . "</td>
                  <td>" . $value->quantity . "</td>
                  <td>" . $value->price . "</td>
                  <td>" . $value->product_id . "</td>";
                        }

                        ?>
                    </tbody>
                </table>
            
            
        </div>
    </main>
    </div>
    </div>